### ISSUE TITLE
Harmony Span Is Not Connected to the webhook

### ISSUE THREAD

**Issue by Jpchico83** [AShifter/harmony-span#11]
when i send the command to the harmony span i can see it on the harmony span app but then nothing happen. i fill like the harmony span is not online.

**Comment by AShifter** [comment]
Thank you for opening an issue!

Could you please share a copy of your config.json with your IFTTT key censored as well as logs from HarmonySpan?

You're getting feedback in the console when you press buttons on the remote, correct?

Thank you again!

**Comment by Jpchico83** [comment]
The issue is fixed now and everything is just working perfectly. Thanks this is a really awesome program I Love It! 👍🏼👍🏼👍🏼

**Comment by AShifter** [comment]
Sounds good! Feel free to open another issue if you run into any problems.
