### ISSUE TITLE
Running Harmony Span on NAS

### ISSUE THREAD

**Issue by JohnnyBoyIsMe** [AShifter/harmony-span#19]
Hi,
Harmony Span is working well, but didn't realise the program always needs to be running order for it to work. 

Is there anyway for this program to run on a NAS directly? i have a QNAP NAS i would like to run it on so i dont need to keep my PC on. 
Im using Harmony Span slightly differently that you may have intended. I have smart switches connected to my subwoofers and exhaust fans. I use HS to turn them on/off when starting an activity. 

Cheers

**Comment by michaelewers** [comment]
Hi,

should be possible:

1. Install up-to-date versions of node.js, npm and git on your NAS
2. git clone the repository and change to the directory on the NAS
3. run "npm ci"
4. run "npm start"

Hit Ctrl-c to stop the service.

That's it.

M.

**Comment by JohnnyBoyIsMe** [comment]
Thanks for the instructions. I'm a bit of a novice when it comes to this type of thing, so if you would be so kind to elaborate a little it would be very helpful. 
 
I have managed to install Node.js v8.9.4.0.1 though it doesn't do anything when i open it.
I have got gitlab installed via ContainerStation and that is working. I found a docker mkenney/npm within ContainerStation,(a simple node container with various wrapper scrips (npm, bower, pulp, etc, - that do not run as root) When installing it asks for containers, not sure what to put here. Is this the right npm thing?

Back to the original instructions. When opening gitlab, i can open either gitlab1, postgresql1 or redis 1, which one do i use? 
Then once open and go into the terminal, i can see there is the clone function in it. What am repository am i cloning, and how to i execute that? Then i need to change the directory, again not sure what to change. 

Then the npm stuff i haven't really looked at yet. 

Sorry for my limited understanding, haven't had the need to do much programming before. 

Thankyou for your help so far. This really is a good thing for home theatre automation.

Cheers

**Comment by michaelewers** [comment]
Sure. Here's a more elaborate list. I'm afraid I don't own a QNAP-NAS, so I have to be somewhat generic. Hope it makes sense to you.
You don't need gitlab, postgres or redis.
node a.k.a. node.js is a JavaScript-runtime environment. Harmony-Span has been coded in JavaScript.
npm is a package-manager for node that let's you install dependencies and run harmony-span.

1. Log into your NAS with a SSH- or Telnet-client. Google "QNAP SSH" for detailed instructions. You should end up with a command line prompt.
2. Check if node is installed by typing "node --version" (should output the version of your node installation)
3. Check if npm is installed by typing "npm --version"
4. Check if git is installed by typing "git version"
If any of the three is not installed, google for "QNAP install node.js" and "QNAP install git command line client"
5. Type "git clone https://github.com/AShifter/harmony-span.git" and wait for git to finish downloading the source code of harmony-span
6. Type "cd harmony-span" to change to the directory
7. Type "npm ci" to let npm download some stuff that harmony-span needs to run. You can ignore any warnings. But if it fails (with an error message), it very likely won't work on your NAS.
8. Type "npm start" to start the tool
9. On your notebook / PC, open a webbrowser and go to "http://your-nas-ip-address:8060/config"

That's it.

**Comment by RolfvanderKwaak** [comment]
> Sure. Here's a more elaborate list. I'm afraid I don't own a QNAP-NAS, so I have to be somewhat generic. Hope it makes sense to you.
> You don't need gitlab, postgres or redis.
> node a.k.a. node.js is a JavaScript-runtime environment. Harmony-Span has been coded in JavaScript.
> npm is a package-manager for node that let's you install dependencies and run harmony-span.
> 
> 1. Log into your NAS with a SSH- or Telnet-client. Google "QNAP SSH" for detailed instructions. You should end up with a command line prompt.
> 2. Check if node is installed by typing "node --version" (should output the version of your node installation)
> 3. Check if npm is installed by typing "npm --version"
> 4. Check if git is installed by typing "git version"
>    If any of the three is not installed, google for "QNAP install node.js" and "QNAP install git command line client"
> 5. Type "git clone https://github.com/AShifter/harmony-span.git" and wait for git to finish downloading the source code of harmony-span
> 6. Type "cd harmony-span" to change to the directory
> 7. Type "npm ci" to let npm download some stuff that harmony-span needs to run. You can ignore any warnings. But if it fails (with an error message), it very likely won't work on your NAS.
> 8. Type "npm start" to start the tool
> 9. On your notebook / PC, open a webbrowser and go to "http://your-nas-ip-address:8060/config"
> 
> That's it.

Super instruction for newbees! Thanks Michael

**Comment by coldfire88** [comment]
Hi, 

any chance to get some instruction for installing this on Linux, or adding it to Home assistant, I'm a total noob with both :(

**Comment by gklank** [comment]
Hi Mike,

super tool - great - super instruction and I got it up and running.

May I ask you if you give me some instructions how to install it in an existing node-red environment / server?


Regards,

Gerhard
