### ISSUE TITLE
universal devices isy 994

### ISSUE THREAD

**Issue by hmatos-rogers** [AShifter/harmony-span#2]
Hi, 

I'm attempting to use the REST interface on my ISY 994 -- I use the url below as an example.

url: http://192.168.7.66/rest/nodes/18733/cmd/DON

I'm running into an issue where the url I put into the config.json for "Play" (example), does not seem to work. I can see "Play" received by harmony-span, but the url doesn't seem to be used/followed.  I go into chrome and type in the same url and my scene commands execute as expected.

Thanks,

**Comment by AShifter** [comment]
Thanks for starting the issue.

Do you have any way of making sure that HarmonySpan is able to make any other requests out into your network/an online service like IFTTT?

Looking through the documentation for the ISY REST interface it only responds to HTTP GET requests, while HarmonySpan currently only has the ability to send POST requests. Looks like everything is good on your side. I'll try to fix this soon.

Apologies for the late response!

**Comment by hmatos-rogers** [comment]
Hi Logan,

Thank you for the quick response.  Its likely a GET/POST issue.  Let me look around and see if I have anything left on IFTTT.

**Comment by AShifter** [comment]
This issue has been fixed in 6cef3a5609fd6bdb09f8cfb45961f9b7c3101766 (HarmonySpan v1.2.2). Binaries will be available at https://github.com/AShifter/harmony-span/releases. New functionality has been added - set the type of request you want to send from HarmonySpan in the `config.json` file - using the `GET` keyword should fix your issue.

Thank you for the help!

**Comment by hmatos-rogers** [comment]
Thanks Logan!  I’ll take a look when I get home— awesome turnaround!

**Comment by AShifter** [comment]
No problem! Let me know if you have any more questions/concerns and feel free to reopen this issue if you run into any other issues.
