### ISSUE TITLE
Add MQTT-Mode

### ISSUE THREAD

**Issue by michaelewers** [AShifter/harmony-span#21]
Changing the tool so that it just creates MQTT-messages whenever a button is pressed would make it incredibly flexible. E.g. it'd be easy to integrate with [Node-RED](https://nodered.org/), allowing for integrating with all kinds of tools / webhooks / frameworks etc.
@AShifter Would you mind if I'd provide a pull-request for that?

**Comment by AShifter** [comment]
Feel free! You might be able to tell that I haven't had enough time to maintain this project haha. Thank you for all of your help, especially with other users. 😄

**Comment by michaelewers** [comment]
Just for reference: I've provided a PR here that adds MQTT-support:
https://github.com/michaelewers/harmony-span/tree/issue/%2321

**Comment by michaelewers** [comment]
Fixed
