### ISSUE TITLE
Binaries are not working

### ISSUE THREAD

**Issue by Jelleeelco** [AShifter/harmony-span#4]
Hi,

I wanted to try this amazing project, but unfortunately, the ZIP files for MAC/Windows/Linux are not valid...
Is it possible to upload them again?

Many thanks!
Jelle..

**Comment by AShifter** [comment]
Thanks for opening an issue.

What release were you trying to run? What kind of issue did you run into?

**Comment by Jelleeelco** [comment]
Hi Logan, 
Thanks for replying so quickly! The issue is already when downloading the .zip files. I can't extract them due to an error ("Windows cannot open the folder, the compressed (zipped) folder is invalid").

I tried on two window machines and with two different zip-extractors. I tried the Linux, Mac and Window zipfiles. The Source code and source code tar.zip file are OK.
Rgds
Jelle..

**Comment by AShifter** [comment]
Try taking each binary and opening them with the tar command (`tar -xvzf HarmonySpan_Win_x64.zip` for example).

**Comment by AShifter** [comment]
All good. You can get Tar binaries for Windows here; http://gnuwin32.sourceforge.net/packages/gtar.htm

**Comment by AShifter** [comment]
Repackaged the binaries as both Windows ZIP files and tar files. The ZIP files should open properly on your system. Thanks for the feedback!
