### ISSUE TITLE
Adding Harmony Span fails using Hub

### ISSUE THREAD

**Issue by Jelleeelco** [AShifter/harmony-span#5]
Please close if this is NOT part of the functionality. I don't have a remote I can attach via USB. When selecting 'Scan for Devices' it asks to connect the hub via USB. I did. Hub is connected to the computer where Harmony Span is running on.

When typing "HTTP://localhost:8060" in chrome it finds the XML, that seems to work. Did not change config.js. 

MyHarmony does not find the server running. Will try with server running on different PC and looking from different PC.

**Comment by AShifter** [comment]
Thanks for leaving the issue. Just to be sure, you're using the MyHarmony desktop software, correct? Make sure there isn't anything setup in your network that isn't allowing SSDP (239.255.255.250) traffic.

**Comment by Jelleeelco** [comment]
Hi,

Worked....here are my findings / questions. I attached the hub to the PC and run the MyHarmony software.

- when running the Harmony Span server and MyHarmony on the same Windows machine, it would not find the Roku device
- when running server on a different windows machine, it would find it immediately and I could add the device. I performed a Sync from MyHarmony to the hub
- Detached the hub from the PC and put it back in its place. Synced again from the mobile app (don't know if that was needed)
- Device is in my list of devices from the app
- If I go to devices in the App, select the Roku device and press buttons (from within the app) all buttons are registered
- when playing Activity Netflix, no button was recognized

Question: should I add the Roku device to each activity I want to control ?

**Comment by AShifter** [comment]
Fantastic! Sounds like it's synced successfully. I'm not sure why it had a problem running on the same machine - it could have just come down to your network configuration. Glad you're all setup now.

The next step is to start adding the Roku HarmonySpan device to each of your activities and start creating sequences for each activity - the idea being that when you press a button (like the pause button) it'll press both the Pause button on your media device, as well as a button in your HarmonySpan config that's tied to a desired webhook (such as one from IFTTT).

I'll be writing more elaborate documentation on the entire setup process on the Harmony side very soon.

Feel free to reopen this issue if you run into any other trouble and thank you for the help!
