### ISSUE TITLE
Button "Pauze" displays as "Play", 'Options' as 'Info'

### ISSUE THREAD

**Issue by Jelleeelco** [AShifter/harmony-span#6]
Hi Logan,

Not sure if this is an issue as the command Play/pauze might be the same on the Roku. All buttons show-up correctly in the server, except 

'pauze': it shows 'play'. 
'options': it shows 'Info'

Not sure if this is a real problem,  as in the harmony app you can create a sequence and have the harmony send any other command when pressing 'pauze'. For instance, 'up' or 'select'. 

I have the server now running at a headless raspberry pi.

Cheers
Jelle..

**Comment by AShifter** [comment]
Thanks for reporting this issue!

Yep, this is intended behaviour as the Roku remote only has a single Play/Pause toggle button. You're completely correct in knowing that you can assign any button press to the Harmony's Pause and Play buttons via activities.

I'll write some more documentation to clarify things here! Thank you so much!
