### ISSUE TITLE
Pause button on Roku shows as Play on the console 

### ISSUE THREAD

**Issue by ziadmalik** [AShifter/harmony-span#9]
Hi,

Great project!  Thanks so much for creating this :)
I am running HarmonySpan v1.2.2, and when I press Pause icon on the roku device in my My harmony mobile app, the console shows that I am depressing Play.  Play works as intended, and I cannot see Pause as a section in the jason.config.  Am I doing something incorrectly?

**Comment by AShifter** [comment]
Thank you for opening an issue!
This is intended behavior - a real Roku remote only has a single button that acts as both Pause and Play. Imagine the names of these buttons just being aliases that let you connect between your Harmony Remote and your webhooks. In our theater, the DirectionLeft button powers on all of our lights and DirectionRight turns them all off.
